language: python
python:
  - "2.7"
# command to install dependencies
install: 
 - "pip install -r requirements.txt"
 - "pip install -r test-requirements.txt"
 - "pip install tox
script: "tox --notest"
