language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
- pip install tox
script: tox --notest
deploy:
  provider: pypi
  user: kstaniek
  password:
    secure: enJNDD+0mEsfOyzTt2hVVpsxwgzWQmvpjCSJZWkvwoRt+mhwrgePrhcbkLEtfmE8CZ8ySdaILcNcZP3EDyWIHAjF69pYEf08XGEzJcaSkJsP0Ti+sK8KC1Cow/VzL76n9uV5hCR2rYNufP3uIXid0FabdjAtDS67++PPXiP6HaupQIla4zIk96O8G7WFcVKMc4mD9sQmteFBQ7SbR6EyZonmkBk3sjGtlOehJNSUc1dFDVynprkcjrCjmtyFkHx4SHjDEsIRGiXZk3qVThDkHsrqq6dGPhutjRa2eDOy4LEp9uGhUwyPNtJg2Y7gwOKnVGpI92hBcvWuQ4eZf1bHAOT5jx8rulpruNg40quuE2eDXRx/FBZo3njlBXVWWyLuP+9UP9llxXb2VE5wjyJodzS1hzt2qpoV3m2WIX+NIYVVWnEtambvSs6Yq+ZdAajwrgWykY2C+ztYeec+AjJudsVBD79Qnv9x4I53zftVMcdGisiU4tWFEFNxU5UqJMwJMlUrrROrO2vW6ITo9NzS6Yp9oBZp7lkGh+8Ivue8fytApKZdNkkoubaLZ0HmUwL/dE00VJ3JGXnfW8U/0vMzU/sVcfS4/YcrNTH6FD1ImB53zwnw4PTpjUFNIrSAEgTPhMCJ7JkRITde4U8M6H+rWSbixb7IN33yHqAQpsZOU8s=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: kstaniek/condoor
